site_name: Yosai
repo_url: https://github.com/yosaiproject
#theme:  bootstrap
markdown_extensions:
  - fenced_code
  - codehilite:
        noclasses: True
        pygments_style: monokai
  - admonition

pages:
- Home: index.md
- Get Started:
    - Introduction: intro.md
    - Installation and Setup:  installation_setup.md
    - Quick-Start:  quickstart.md
- Documentation:
    - Authentication: authentication.md
    - Authorization: authorization.md
    - Session Management: sessionmanagement.md
    - Event Processing: events.md
    - Serialization:  serialization.md
    - Architecture Overview:  architecture.md
    - Web Integration:  web.md
- More:
    - Development Status:  devstatus.md
    - Library:  library.md
    - Community: community.md
    - Contributing:  contributing.md
    - Code of Conduct:  code_of_conduct.md
    - Credits: credits.md
